### ISSUE TITLE
Couldn't start any minecraft version downloaded from other launcher

### ISSUE THREAD

**Issue by Xottab-DUTY** [dedepete/FreeLauncher#24]
```
[E] Error: Could not create the Java Virtual Machine.
[E] Error: A fatal exception has occurred. Program will exit.
[E] Unrecognized option: --username
============
Process info:
  Minecraft version/type:1.11/release
  Executable file: "F:\Program Files\Java\jre1.8.0_131\bin\java.exe"
  Arguments: "-Djava.library.path=F:\Users\Xottab_DUTY\AppData\Roaming\.minecraft\natives\ -cp  net.minecraft.client.main.Main --username Xottab_DUTY --version "Последняя версия" --gameDir F:\Users\Xottab_DUTY\AppData\Roaming\.minecraft\ --assetsDir F:\Users\Xottab_DUTY\AppData\Roaming\.minecraft\assets\ --assetIndex 1.11 --uuid sample_token --accessToken sample_token --userType offline --versionType release"
  Exit code: 1
============
```
Version in this log was downloaded not from FreeLauncher, but from TLauncher. When I deleted version and redownloaded it everything started to work.
Here you want watch the difference between version's jsons:
NewLauncher https://gist.github.com/Xottab-DUTY/ca59f034dafbd4dd2a4a84d45d7ea243
TLauncher https://gist.github.com/Xottab-DUTY/b3d7338d6691be8cd4e83c14b5b9b774

It would be fine if NewLauncher can parse all the json mess despite the difference in launchers

P.S. Забыл, что я мог и по-русски написать. Когда опомнился уже стало лень переписывать :D

**Comment by dedepete** [comment]
Смог воспроизвести проблему, спасибо. Сейчас AppVeyor CI выполнит сборку последней фиксации.

**Comment by dedepete** [comment]
Доступно для загрузки:
https://ci.appveyor.com/project/dedepete/freelauncher/build/job/9nse9okgv78ecgtx/artifacts

Дайте знать, если всё не/будет работать.

**Comment by Xottab-DUTY** [comment]
Спасибо за быстрый ответ!
Посмотрел лог, но... как-то не срослось понять его. В чём проблема была?

**Comment by dedepete** [comment]
Проблема заключалась в том, что Mojang начали использовать новую переменную  `path` в элементах массива `libraries`, но разработчик TLauncher проигнорировал или не счёл необходимым это изменение, что повлекло отсутствие этой переменной в конфигурации версии игры.  
У Вас этот недочёт проявлялся на стадии запуска из-за наличия скачанных библиотек, но у меня он проявился ещё на стадии их проверки.  
Исправил банальной проверкой наличия этой переменной.

**Comment by Xottab-DUTY** [comment]
Спасибо. Теперь понятно)
