### ISSUE TITLE
Close log tab even if game is launched or log is being printed

### ISSUE THREAD

**Issue by Xottab-DUTY** [dedepete/FreeLauncher#25]
Про закрытие лога во время игры: ещё в Luncher'е лог подвисал игру. Судя по #18 этого уже не должно быть. Но всё таки хотелка есть закрывать лог))

Но это ладно. Бывает зафлуженный/заспамленный лог или просто там много записей и ждать пока >10000 строк выведется.. не очень.

Игра уже закрылась, но лог всё ещё идёт от момента когда она только открывалась
https://yadi.sk/i/MnUjOFS93KJeEW

**Comment by dedepete** [comment]
Я постараюсь оптимизировать вывод логов в ближайшем обновлении.

**Comment by Xottab-DUTY** [comment]
Буду ждать!

**Comment by dedepete** [comment]
В качестве временного решения можно отключить вывод лога в консоль.

**Comment by dedepete** [comment]
Вроде что-то исправил. Пожалуйста, проверьте.  
Пока что до ответа оставляю вопрос открытым.  
https://ci.appveyor.com/project/dedepete/freelauncher/build/39-master/job/owb1of8ubibhj80g/artifacts

**Comment by Xottab-DUTY** [comment]
Да, лог выводится в реальном времени. Бывает только, что FreeLauncher вылетает (Прекращена работа программы). Причину вылетов не могу сказать.....

**Comment by dedepete** [comment]
Как часто и при какой операции?

_Отправлено с моего Yota Devices Limited YD201 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Xottab-DUTY** [comment]
Трудно заметить какую-то периодичность в этом. Вылетало в прошлой сборке раза два при нескольких вкладках с логом. (Игра уже закрылась, но лог ещё выводился, поэтому я не смог их закрыть)
Про релиз 0.1.6 не скажу, т.к. не помню.

В этой сборке вылет произошёл при одной вкладке.

Вылеты происходили, когда игра только загружалась.

Если смотреть по прошлой сборке, то бывало, что резко из игры выпуливалось куча лога (В очереди было, скажем, 50 и, вдруг, стало 200, потом бац и в два раза больше.... Таким образом очередь доходила до >10000 строк). Может быть лаунчер не успевает где-то принимать строки и/или происходит переполнения какое-то? Или может быть что-то иное.

**Comment by Xottab-DUTY** [comment]
Что насчёт возможности закрытия вкладки с логом, когда игра запущена? Чтобы играть без лога)

**Comment by dedepete** [comment]
Хм, неплохо было бы. Добавлю в to do.

**Comment by dedepete** [comment]
Если всё будет стабильно, то можно выходить в релиз.  
https://ci.appveyor.com/project/dedepete/freelauncher/build/job/da64nuts72r88u5f/artifacts

**Comment by dedepete** [comment]
@Xottab-DUTY, так оно работает? Проблему можно закрывать?

_Отправлено с моего YotaPhone YD201 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Xottab-DUTY** [comment]
Только что словил связанное с этим исключение.
Как воспроизвести:
Запустить игру (запускал 1.12), дождаться появления главного меню, закрыть вкладку с логом, потом закрыть саму игру.

> Исключение: Возникло исключение "System.ArgumentOutOfRangeException" в mscorlib.dll ("Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции."). 

P,S. сам собрал и запускал из под VS2017

**Comment by dedepete** [comment]
Не могу воспроизвести проблему. На какие строки ругается?

**Comment by Xottab-DUTY** [comment]
Два дампа:
Первый: https://yadi.sk/d/DjzuistE3LVV9n
Второй (там я нажал "Продолжить" после первого исключения): https://yadi.sk/d/JBepFN093LVVCh

**Comment by dedepete** [comment]
У вас включено автоматическое закрытие вкладки при успешном завершении игры? :D

**Comment by Xottab-DUTY** [comment]
Да :D

**Comment by dedepete** [comment]
В последней фиксации поправил.

**Comment by dedepete** [comment]
@Xottab-DUTY теперь-то закрыть можно? :D

**Comment by Xottab-DUTY** [comment]
Не вылетает. Теперь всё работает =)

P.S. надо сказать, что собранный с какой-то предыдущей фиксации лаунчер не один раз вылетел на моей перегруженной модами сборке. (91 мод) Не могу сказать из-за чего вылетал и может быть вылетов уже не будет, но буду смотреть, вдруг всё-таки вылетит.
Однако, это уже другая история.
