### ISSUE TITLE
Forge and LiteLoader combination is not working.

### ISSUE THREAD

**Issue by Xottab-DUTY** [dedepete/FreeLauncher#26]
Имеется версия майнкрафта с Liteloader зависящая от версии майнкрафта с Forge, которая, в свою, очередь зависит от оригинальной версии майнкрафта (номер не важен, но в данном случае 1.12)

Зависимости:
`ForgeLiteloader.json -> Forge.json -> Vanilla.json`

Лаунчер не смог запустить такое с двойной зависимостью.. (Возможно причина другая)

Как воспроизвести?
> Установить Forge через установщик, и поверх него установить LiteLoader через установщик.
> ???
> Profit!

Опять _TLauncher:_
Учитывая то, что он из зависимых версий делает независимые, он, смог запустить эту связочку.
Но именно эта особенность мне и не нравится. Это сведение на нет преимуществ системы зависимостей.

_Несколько полностью одинаковых jar'ов в подпапках папки versions и засовывание туда же рядом папки natives, вместо использования .minecraft/natives... не очень._ 

P,S, А после того, как TLauncher перебрал .json, то FreeLauncher уже может запустить; но, что интересно, LiteLoader не загружается, хотя в консоли лаунчера он указан в аргументах..

**Comment by dedepete** [comment]
Я закончил подавать документы в ВУЗы и готов снова вернуться к работе.  
Пожалуйста, попробуйте использовать [LiteLoader как мод](http://www.liteloader.com/explore/docs/user:install:forge#mod).  
Я постараюсь воспроизвести эту проблему.

**Comment by Xottab-DUTY** [comment]
Ну что там, доктор? =)

**Comment by dedepete** [comment]
Глухо, как в танке. Теряющиеся аргументы исправить получилось, но запускаться игра всё равно отказывается.

**Comment by dedepete** [comment]
Вру, что-то есть.

**Comment by dedepete** [comment]
![image](https://user-images.githubusercontent.com/1936922/28611642-283f8a54-71f5-11e7-96cc-b5170c9082b1.png)

**Comment by dedepete** [comment]
Проверяйте: https://ci.appveyor.com/project/dedepete/freelauncher/build/41-master/job/7a425c2p0tt62m2c/artifacts

**Comment by Xottab-DUTY** [comment]
Игра запустилась, всё работает. Проблема исправлена.
Правда, меня немножечко смутила сия строка:
`[O] [16:36:25] [main/INFO]: [net.minecraft.client.main.Main:main:55]: Completely ignored arguments: [offline, , sample_token, , Xottab_DUTY, , 1.12, sample_token, Forge]`
Меня смутило не то, что игра пропустила аргументы, а то, что там есть пустые аргументы.. Но, может быть это и нормально.
