### ISSUE TITLE
Minecraft News are available no more.

### ISSUE THREAD

**Issue by Xottab-DUTY** [dedepete/FreeLauncher#29]
Похоже, что блог, который используется для новостей, больше не обновляется..

**Comment by dedepete** [comment]
Грустно. Кажется, Mojang переезжают на новый лаунчер, который разрабатывали с недавних пор.

**Comment by dedepete** [comment]
Похоже, что Mojang окончательно забили на какое-либо обновление этого блога. Придётся либо искать альтернативный блог, либо делать его на GitHub самому.

**Comment by Xottab-DUTY** [comment]
Мне кажется, должно быть какое-то окошко новостей и в новом лаунчере майнкрафта. Значит, должен быть и какой-то другой блог... или что-нибудь ему подобное..

Если делать свой, то в этом есть плюс: собственно, можно делать с ним что угодно.

**Comment by dedepete** [comment]
Скорее всего используется API с minecraft.net, который и возвращает при запросе новости.

_Отправлено с моего YotaPhone YD201 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Xottab-DUTY** [comment]
Я тоже об этом думал и, мне кажется, так и есть. Нужно будет найти способ использовать этот апи, если он есть)

**Comment by dedepete** [comment]
Вообще с поддержкой нового лаунчера Mojang всё плохо, т.к. `.json` со списком профилей кардинально изменился. Похоже, что придётся начинать делать dotMCLauncherV2, а вместе с ним и новый лаунчер. 😢  
С одной стороны, это даже неплохо, потому что получится провести работу над ошибками текущего dotMCLauncher и безболезненно переехать на WPF с WinForms.  
С другой стороны, это опять же большая работа. И даже не по части программирования, сколько по части освоения WPF.

**Comment by Xottab-DUTY** [comment]
Что касается WPF: а это не повысит требования к наличию определённой версии .NET Framework?

А что касается dotMCLauncherV2, то я бы задел ещё и YaDra4il: не стоит ли его переименовать? Всё таки Иггдрасиль, Мировое древо, все дела.. Да и просто не очень приятно выглядит название.

**Comment by dedepete** [comment]
.NET Framework 4.5 останется обязательным требованием к системе.  
dotMCLauncherV2 будет разбит на dotMCLauncher.Authorization и dotMCLauncher.Core. Все неприличности уберутся/скроются :D

**Comment by dedepete** [comment]
**UPDATE**: the used URL is available no more.  
Changing the status of this issue to critical.
