### ISSUE TITLE
Support ely.by accounts

### ISSUE THREAD

**Issue by Xottab-DUTY** [dedepete/FreeLauncher#31]
Было бы неплохо иметь помимо oflline и online(лицензионного) аккаунта иметь возможность использовать аккаунт ely.by.

Документация: http://docs.ely.by/minecraft-auth.html

Низкоприоритетно.

**Comment by dedepete** [comment]
Я очень давно слышал про эту систему и её популярность, но делать реализацию не буду.  
На [RuBukkit](http://rubukkit.org/threads/gotovaja-sistema-skinov-i-avtorizacii-ely-by.102863/) приведено довольно большое количество причин, почему эту систему невыгодно реализовывать.  
Однако, полагаю, не были сказаны причины, почему это невыгодно делать неофициальным лаунчерам. Постараюсь разложить всё по полочкам:
1. Все версии, используемые во FreeLauncher, находятся на серверах Amazon, что обеспечивает огромнейшую стабильность в работе лаунчера. Сервера Ely.by находятся явно не на таких серверах, что может резко сказаться на стабильности.
2. **Версии с авторизацией – это вшитые модификации в файлы версии и конфигурации**. FreeLauncher поддерживает только официальные версии, загружаемые с серверов Amazon. Для того, чтобы добавить модифицированные версии, нужно ставить отдельный сервер, который будет обеспечивать доступность как версий, так и библиотек. Хороший и стабильный сервер стоит немалых денег, что неприменимо для проекта, который не имеет дохода. Добавлять рекламу недосерверов-однодневок и всяких казино-рулеток в целях его появления я тоже не буду. Отсутствие навязчивой рекламы – моя цель, которую я поставил перед своей разработкой, и я от неё не отступлюсь.
3. Ely.by – проект с закрытым исходным кодом. На данный момент всё, что используется в проекте FreeLauncher, так или иначе имеет открытый исходный код (или большое доверие, как в случае с Telerik RadControls, но и от этой библиотеки компонентов я планирую отказаться в пользу открытого MahApps.Metro).

Надеюсь, что этих причин будет достаточно, чтобы войти в положение дел.

Кроме того, есть другие причины, о которых я, увы, не могу поведать.

Я ничего не имею против ответвления, которое будет обслуживаться другими разработчиками, но не мной.
