### ISSUE TITLE
Can't load designer of LauncherForm.cs and other forms.

### ISSUE THREAD

**Issue by VictoryAndGlory** [dedepete/FreeLauncher#32]
The error code:
Message Value cannot be null.
Parameter name: instance			0	

And Visual Studio didnt point where the error occured.
Tried to remove every element in design file one by one didnt fix it.
Tried to remove all of it yet it didnt fix it.

I also installed Telerik Winforms UI yet it didnt work.
I unloaded/loaded references again didnt work.

**Comment by dedepete** [comment]
Have you installed the solution directly from GitHub client?

**Comment by Xottab-DUTY** [comment]
I have the same problem. Downloaded via Github client (just pushed the "Open in Desktop" button)

**Comment by VictoryAndGlory** [comment]
Yes, I installed the solution directly from GitHub.

**Comment by dedepete** [comment]
Hmm, I'm afraid I can't reproduce this issue.  
Looks like this is because your Visual Studio hasn't got Telerik tools installed. Please, confirm.  
If so, I'm unable to do anything.

**Comment by VictoryAndGlory** [comment]
Actually I have telerik tools in my visual studio.

**Comment by dedepete** [comment]
Oops, accidentally closed this Issue.  
I can't still reproduce the issue, but if you think that this is because of license, you can try to remove this line.
https://github.com/dedepete/FreeLauncher/blob/09b0b0c05d1e88114fe253782a49da485fef96b7/src/FreeLauncher/FreeLauncher.csproj#L164
