### ISSUE TITLE
Crash on new snapshots

### ISSUE THREAD

**Issue by Harry09** [dedepete/FreeLauncher#34]
Since snapshot 17w43b, minecraft has changed arguments list, which crash launcher.

**Comment by dedepete** [comment]
Okey, here's a roadmap for this issue:
____
## Examine
- [X] Examine the new format used in the latest snapshot build _(currently `18w02a`)_.
- [ ] Examine if previous game builds were updated to the new format.
    - [ ] snapshot
    - [ ] release
    - [ ] old_beta
    - [ ] old_alpha
- [ ] Examine if Minecraft Forge and other custom builds were updated to the new format.
    - [ ] Minecraft Forge
    - [ ] OptiFine
    - [ ] LiteLoader

## Implement
- [ ] Implement new format.
    - [ ] Remove old implementation, if not used anymore.

## Test
- [ ] Test the new implementation.
    - [ ] snapshot 18w02a
    - [ ] latest available build
    - [ ] release
    - [ ] old_beta
    - [ ] old_alpha

____
P.S. Just to forget nothing :P

**Comment by dedepete** [comment]
I'm game.
![](https://user-images.githubusercontent.com/1936922/35889327-2e41c1aa-0bac-11e8-853c-a9c6f3e2e8ad.png)

**Comment by dedepete** [comment]
@Harry09 Feel free to test [the debug build](https://ci.appveyor.com/api/buildjobs/c42lkants6ahdfun/artifacts/src%2FFreeLauncher%2Fbin%2FDebug.zip).

**Comment by Harry09** [comment]
Works fine. Thanks.
