### ISSUE TITLE
High CPU usage after game minecraft launched

### ISSUE THREAD

**Issue by asc7uni** [dedepete/FreeLauncher#36]
FreeLaucher.exe eats one cpu to 100% after game started.
Win 7
0.1.8_master.a0c3d4b7

**Comment by dedepete** [comment]
What is your profile's configuration? What Minecraft version are you running?

**Comment by asc7uni** [comment]
This is screenshot of profile https://imgur.com/a/5qnRW
I think everything is default.
Minecraft is 1.12.2/release. Without mods.
java version "1.8.0_141"

I unchecked "print log to console" here  https://imgur.com/a/3FUtM but nothing changed

**Comment by dedepete** [comment]
That's weird. Does it happens every time you launch the game?  
Please, execute `dxdiag` in Windows CMD and post results here.

**Comment by asc7uni** [comment]
Hi again!

I dig into code a little and found that thread that watch _minecraftProcess is literally infinite loop so 100% load look like expected behaviour.

As all the thread time is only used to check _minecraftProcess status and updating status text and appending logs I think it will be safe to give up some CPU time. 
You can just add 1 msec or even more  sleep delay into loop.
It will still do all thread job ~1000 times/sec

See https://github.com/dedepete/FreeLauncher/blob/e219446def9f17b04f6b1f71be67448a8daefcb5/src/FreeLauncher/Forms/LauncherForm/LauncherForm.cs#L1222

You can add Thread.Sleep(1); inside while body. It fixed CPU load for me. And everything else still works. 


P.S. I can be wrong in everything. I don't know C# and Win32 specific programming, but adding sleep() to thread body is common technique to reduce load.

**Comment by dedepete** [comment]
@asc7uni This is a really good find out!  
I have never experienced over high CPU usage, but adding `Thread.Sleep(1)` decreased it by 5-13% for me.  
Thank you! I'll commit the changes in 10 minutes or so.
