### ISSUE TITLE
Where to get dotMCLauncher??

### ISSUE THREAD

**Issue by GabrielTK** [dedepete/FreeLauncher#4]
Good afternoon,
Sorry to ask, but, is dotMCLauncher a library??? If yes, where can we get it??? I'm writing a launcher for a server.

**Comment by dedepete** [comment]
You can find dotMCLauncher in _/lib/_ directory.

**Comment by oliwerbig** [comment]
Is dotMCLauncher written by you?

**Comment by dedepete** [comment]
@olinagy2 sure.
