### ISSUE TITLE
Implement Profiling V2.

### ISSUE THREAD

**Issue by dedepete** [dedepete/FreeLauncher#41]
```json
{
  "selectedProfile": "Latest Release",
  "profiles": {
    "<random-guid:0>": {
      "type": "latest-release",
      "lastUsed": "1970-01-01T00:00:00.001Z"
    },
    "<random-guid:1>": {
      "type": "latest-snapshot",
      "lastUsed": "1970-01-01T00:00:00.000Z"
    },
    "FreeLauncher": {
      "name": "FreeLauncher",
      "type": "custom",
      "created": "2018-03-11T18:04:56.624Z",
      "lastUsed": "2018-03-11T18:05:24.153Z",
      "icon": "Wool",
      "lastVersionId": "latest-release",
      "gameDir": "C:/Users/Igor/AppData/Roaming/.minecraft"
    },
    "Latest Release": {
      "name": "Latest Release",
      "type": "custom",
      "created": "2018-03-11T18:04:56.624Z",
      "lastUsed": "1970-01-01T00:00:00.000Z",
      "lastVersionId": "latest-release"
    },
    "Latest Snapshot": {
      "name": "Latest Snapshot",
      "type": "custom",
      "created": "2018-03-11T18:04:56.624Z",
      "lastUsed": "1970-01-01T00:00:00.000Z",
      "lastVersionId": "18w10d"
    }
  },
  "settings": {
    "locale": "ru",
    "showMenu": true,
    "keepLauncherOpen": false,
    "showGameLog": false,
    "crashAssistance": false,
    "enableAnalytics": false,
    "enableHistorical": true,
    "enableSnapshots": true,
    "enableAdvanced": true
  },
  "launcherVersion": {
    "name": "2.0.1003",
    "format": 21,
    "profilesFormat": 2
  },
  "authenticationDatabase": {
    "<random-guid?:2>": {
      "accessToken": "<accessToken>",
      "username": "<Mojang username or legacy username>",
      "profiles": {
        "<UUID>": {
          "displayName": "dedepete"
        }
      }
    }
  },
  "selectedUser": {
    "account": "<random-guid?:2>",
    "profile": "<UUID>"
  },
  "analyticsToken": "f0ckth34n41ytics",
  "analyticsFailcount": 0,
  "clientToken": "<sessionToken?>"
}
```

**Comment by Xottab-DUTY** [comment]
Было бы неплохо вместе с этим сделать #30

**Comment by dedepete** [comment]
@Xottab-DUTY #30 имеет более высокий приоритет для меня по ряду причин.  

FreeLauncher вряд ли будет работать на новой системе профилирования полностью, т.к. в ней очень многие значения вынесены за рамки какого-то конкретного профиля и теперь распространяются на всё (например, включение отображения в выпадающих списках старых версий и снапшотов).  
Хотя сама концепция хранения всех параметров лаунчера в одном файле с профилями мне очень нравится. Я бы использовал её и раньше, но боялся конфликтов с официальным Джебовским лаунчером.  
V2 тут будет скорее в качестве прослойки для совместимости с новым лаунчером. Например, портировать профили какого-нибудь Forg'a или OptiFin'a, и наоборот -- перенести профили FreeLauncher обратно в официальный лаунчер.

Да и сам я столкнулся с проблемой быстро отредактировать или удалить какой-нибудь профиль. :)

**Comment by Xottab-DUTY** [comment]
@dedepete, уже достаточно давно не притрагивался к Minecraft...
А что там в лаунчере поменялось?

**Comment by dedepete** [comment]
@Xottab-DUTY почти что всё. Я даже сам ещё до конца не разобрался.
Из того, что сразу же бросилось в глаза:
- Добавили аналитику (`"analyticsToken": "f0ckth34n41ytics"`);
- Добавили просмотр и загрузку скинов;
- Добавили ПРОСТО УЙМУ предупреждений при редактировании почти что каждого параметра;
- Убрали очень много настроек в самые дальние углы, чтоб чайники не натыкали чего лишнего;
- Убили старый блог MCUpdate.

![default](https://user-images.githubusercontent.com/1936922/37293941-c8785bba-2625-11e8-845c-208e1b4d57f5.png)

Из вкусного только обновление формата хранения профилей.

**Comment by Xottab-DUTY** [comment]
@dedepete, много, однако. изменений..
> Добавили аналитику
f0ckth34n41ytics. Да, надеюсь оно будет работать с вырезанной аналитикой =)
