### ISSUE TITLE
Problem with usernames in launcher.

### ISSUE THREAD

**Issue by neckoed** [dedepete/FreeLauncher#42]
My windows profilename consists of two words. And I got this error message while starting minecraft. Username is Michael Zorn, and got this error message: 
[O] 
[E] Error: Could not find or load main class Zorn\AppData\Roaming\.minecraft\natives\
[E]

**Comment by dedepete** [comment]
Can you post logs from the main console, please?

**Comment by dedepete** [comment]
@neckoed Should be fixed: https://ci.appveyor.com/api/buildjobs/ccsfvjjgojlxsdv9/artifacts/src%2FFreeLauncher%2Fbin%2FDebug.zip
