### ISSUE TITLE
HELP Implementation

### ISSUE THREAD

**Issue by brutalzinn** [dedepete/FreeLauncher#58]
Could you do an implementation tutorial?

How do I implement this launcher in my project?
There are many specific variables and I can not open the form design. As a command I execute to open minecraft with forge in offline mode and in user mode through core? Please, if you can, help.

THANKFUL.

**Comment by dedepete** [comment]
Feel free to examine the code by yourself.

**Comment by brutalzinn** [comment]
The problem is that I do not have the freedom to modify the launcher. I do not have paid telekit license. This is making me very sad .. I finally found an interesting launcher and I am not able to implement it. I get the message that I need to buy telerik every time I open the program.

**Comment by brutalzinn** [comment]
could you make a version without using telerik?
