### ISSUE TITLE
Where are the profile-informations stored?

### ISSUE THREAD

**Issue by o0Julia0o** [dedepete/FreeLauncher#70]
I have a copy of FreeLauncher.exe here:
D:\FreeLauncher.exe

I start this exe. I add a profile named dedepete1.

I have another FreeLauncher.exe here:
E:\FreeLauncher.exe

i start this exe. And i still have the profile named dedepete1. 

That´s annoying for wanting to have a portable launcher. Can you make an ini-file next to the FreeLauncher.exe, where the profiles are stored?

Where are they stored now?

A quick-launch option in this ini-file would be awesome. So you start Minecraft with the last used profile and minecraftversion. Both infos could be saved in this ini-file, too.

thx!

**Comment by o0Julia0o** [comment]
The information is stored on C:\Users\USERNAME\AppData\Roaming\.minecraft\freelauncher
configuration.json and users.json

It would be very useful, to store this information in the path of the FreeLauncher.exe

**Comment by dedepete** [comment]
See #71.
