### ISSUE TITLE
Make it portable

### ISSUE THREAD

**Issue by o0Julia0o** [dedepete/FreeLauncher#71]
it would be nice, if Freelauncher would be portable. So all the files and folders would be in the folder, where the freelauncher.exe is. So the downlaoded minecraft-files, too.

So without setting a hard path. It must be an option for an relative path.
https://i.imgur.com/2bjNQEL.png
this setting is using the drive where Freelauncher.exe is. But not the whole folder. So if you have the freelauncher.exe in E:\Games\Freelauncher

the minecraft-files are not loaded into  E:\Games\Freelauncher\. They are loaded into: E:\   :(

**Comment by dedepete** [comment]
Making launcher portable is supported by providing additional launch argument `-d` or `--working-directory` with an executable, e.g. `.\FreeLauncher.exe -d "E:\Games\FreeLauncher"`.

**Comment by dedepete** [comment]
Feel free to reopen.

**Comment by o0Julia0o** [comment]
Thx. But so you have always to edit the working-directory-path to the launch argument. So you can´t just copy it from one path to another without editing the launch argument after that.

**Comment by dedepete** [comment]
Simply put BATCH or PowerShell script with an executable and run launcher through it.  
```batch
@ECHO OFF
START "" FreeLauncher.exe '-d \"%CD%\"'
```
or
```powershell
& ".\FreeLauncher.exe" @("-d", "$((Get-Item -Path '.\' -Verbose).FullName)")
```
