### ISSUE TITLE
Minecraft 1.8 and lower not run

### ISSUE THREAD

**Issue by LowSkillGamer** [dedepete/FreeLauncher#8]
[ERROR] Error: Could not create the Java Virtual Machine.
Process exited with error code 1(There could be problems). Session since 18:21:05(0 min. total)

> 	Исключение: Возникло исключение "System.NullReferenceException" в dotMCLauncher.Core.dll ("Ссылка на объект не указывает на экземпляр объекта."). Возникло исключение "System.NullReferenceException" в dotMCLauncher.Core.dll ("Ссылка на объект не указывает на экземпляр объекта.")
>

**Comment by dedepete** [comment]
Исправил, спасибо!
